config/routes.rb
Explainpmt::Application.routes.draw do
  
  root :to => "dashboard#index"
  
  resource :dashboard
  resource :user_session
  
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  
  resources :projects do
    member do
      get :xml_export
      get :audits
      get :team
      get :add_users
      post :update_users
    end
    
    resource :dashboard, :controller => 'dashboard'
    
    resources :acceptance_tests do
      member do
        get :clone_acceptance
      end
      collection do
        get :export
        post :assign
      end
    end
    resources :releases do
      member do
        get :select_stories
        post :assign_stories
        post :remove_stories
      end
      
      resources :stories
    end
    
    resources :initiatives
    
    ## TODO => simiplify the stories routes, too many.
    
    resources :stories do
      member do
        get :audit
        get :take_ownership
        get :release_ownership
        get :assign_ownership
        post :assign
        # put :clone
        get :clone
        put :move_up # Get ready to remove this
        put :move_down # Get ready to remove this
        get :edit_numeric_priority
        put :set_numeric_priority
      end
      
      collection do
        get :search
        get :all
        get :cancelled
        get :export
        get :export_tasks
        get :bulk_create
        post :bulk_create
      end
      
      resources :tasks do
        member do
          get :take_ownership
          get :release_ownership
          get :assign_ownership
          post :assign
        end
      end
      resources :acceptance_tests
    end
    
    resources :milestones do
      collection do
        get :show_all
        get :show_recent
      end
    end
    
    resources :iterations do
      member do
        get :allocation
        get :select_stories
        post :assign_stories
        get :export
        get :export_tasks
      end
      collection do
        post :move_stories
      end
      
      resources :stories
    end
    
    resources :users do
      member do
        get :remove_from_project
      end
    end
  end
  resources :users do
    collection do
      get :forgot_password
      post :forgot_password
      get :reset_password
      put :reset_password
    end
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :story
  belongs_to :owner, :class_name => 'User', :foreign_key => :user_id
  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :story_id
  
  scope :for_user, lambda{ |user| where(:user_id => user.id) }
  scope :complete, where(:complete => true)
  scope :incomplete, where(:complete => false)
  
  def assign_to!(new_owner)
    update_attribute(:user_id, new_owner.id)
  end

  def release_ownership!
    update_attribute(:user_id, nil)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_task, :except => [:new, :create]

  def new
    @story = Story.find params[:story_id]
    @task = Task.new
  end
  
  def edit
    @story = @task.story
  end

  def create
    @story = Story.find(params[:story_id])
    @task = @story.tasks.build(params[:task])
    
    if @task.save
      render_success("New Task \"#{@task.name}\" has been created.") { redirect_to project_story_tasks_path(current_project, @story) }
    else
      render_errors(@task.errors.full_messages.to_sentence) { render :new }
    end
  end

  def update
    @story = Story.find(params[:story_id])
    
    if @task.update_attributes(params[:task])
      render_success("Task \"#{@task.name}\" has been updated.") { redirect_to project_story_tasks_path(current_project, @story) }
    else
      render_errors(@task.errors.full_messages.to_sentence) { render :edit }
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task \"#{@task.name}\" has been deleted."
    redirect_to request.referer
  end

  def take_ownership
    @task.assign_to!(current_user)
    redirect_to request.referer
  end

  def release_ownership
    @task.release_ownership!
    redirect_to request.referer
  end

  def assign_ownership
    @users = current_project.users
    render :partial => "assign_owner_form"
  end

  def assign
    @task.assign_to!(User.find params[:owner][:id])
    redirect_to request.referer
  end

  protected

  def find_task
    @task = Task.find params[:id]
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def link_to_new_task(story)
    link_to "Add Task", new_project_story_task_path(current_project, story), :class => "form popup"
  end

  def link_to_edit_task(task, options={})
    story = task.story
    link_to (options[:text] || task.name), edit_project_story_task_path(story.project, story, task), :class => "form popup edit tip", :title => "edit"
  end

  def link_to_delete_task(task)
    link_to "Delete", project_story_task_path(current_project, task.story, task), :class => "delete popup tip", "data-message" => "Are you sure you want to delete?", :title => "delete"
  end

  def link_to_task(task, options={})
    link_to (options[:text] || task.name), :url => project_story_task_path(current_project, task.story, task)
  end

  def link_to_take_task_ownership(task)
    link_to 'take', take_ownership_project_story_task_path(current_project, task.story, task), :method => :put
  end

  def link_to_assign_task_ownership(task)
    link_to 'assign', assign_ownership_project_story_task_path(current_project, task.story, task), :class => "form popup"
  end

  def link_to_release_task_ownership(task)
    link_to 'release', release_ownership_project_story_task_path(current_project, task.story, task), :method => :put
  end
end

app/views/tasks/_assign_owner_form.html.erb
<%= form_for :owner, :url => assign_project_story_task_path(@project, @task.story, @task) do |f| %>
	<% @users.each do |m| %>
		<%= f.radio_button :id, m.id %>
		<%= f.label :id, m.full_name, :value => m.id, :class => "inline" %>
		<br />
	<% end %>
	<div class="submit">
		<%= f.submit "Assign" %>
	</div>
<% end %>

app/views/tasks/_form.html.erb
<h2>Task Details</h2>
<fieldset>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<%= form.label :description %>
	<%= form.text_area :description %>
	<%= form.label :owner %>
	<%= form.select :user_id, current_project.users.collect {|u| [ u.full_name, u.id ] }, {:include_blank => true} %>
</fieldset>
<fieldset>
	<%= form.radio_button :complete, true %>
	<%= form.label :complete, "Complete", :value => true, :class => "inline" %>
	<%= form.radio_button :complete, false %>
	<%= form.label :complete, "Not Complete", :value => false, :class => "inline" %>
</fieldset>

app/views/tasks/_task.html.erb
<tr>
	<td class="align_left"><%= task.name %></td>
	<%= column_content_for(hide_cols, :project) do %>
	<td class="align_left center"><%= link_to(task.story.project.name, project_dashboard_path(task.story.project)) %></td>
	<% end %>

	<%= column_content_for(hide_cols, :iteration) do %>
	<td class="align_left center"><%= task.story.iteration_id ? link_to_iteration(task.story.iteration) : "Not Assigned" %></td>
	<% end %>

	<%= column_content_for(hide_cols, :story) do %>
	<td class="align_left center"><%= link_to_story_with_sc(task.story) %></td>
	<td class="align_left center"><%= link_to_story(task.story) %></td>
	<% end %>

	<td class="align_left center"><%= task.complete == true ? 'Yes' : 'No' %></td>

	<%= column_content_for(hide_cols, :owner) do %>
	<td class="align_left center">
	<% if task.owner %>
		<%= task.owner.full_name %>
		<%= "(#{link_to_release_task_ownership(task)})" %>
	<% else %>
		<%='None (' + link_to_take_task_ownership(task) + '/' + link_to_assign_task_ownership(task) + ')'%>
	<% end %>
	</td>
	<% end %>

	<%= column_content_for(hide_cols, :action) do %>
	<td class="align_left center tools">
		<%= link_to_edit_task(task, :text => "Edit") %>
		<%= link_to_delete_task(task) %>
	</td>
	<% end %>
</tr>

app/views/tasks/_tasks.html.erb
<% hide_cols ||= [] %>
<table class="sorting" id="task-table">
	<thead>
		<tr>
			<th class="align_left">Task</th>
			<%= column_content_for(hide_cols, :project) do %><th class="align_left center">Project</th><% end %>
			<%= column_content_for(hide_cols, :iteration) do %><th class="align_left center">Iteration</th><% end %>
			<%= column_content_for(hide_cols, :story) do %>
			<th class="align_left center">SCID</th>
			<th class="align_left center">Story</th>
			<% end %>
			<th class="align_left center">Complete</th>
			<%= column_content_for(hide_cols, :owner) do %><th class="align_left center">Owner</th><% end %>
			<%= column_content_for(hide_cols, :action) do %><th class="align_left center tools">Action</th><% end %>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => @tasks, :locals => { :hide_cols => hide_cols } %>
	</tbody>
</table>

app/views/tasks/edit.html.erb
<%= form_for [current_project, @story, @task] do |f| %>
	<%= render :partial => f %>
	<%= f.submit %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for [current_project, @story, @task] do |f| %>
	<%= render :partial => f %>
	<%= f.submit %>
<% end %>