config/routes.rb
Explainpmt::Application.routes.draw do
  
  root :to => "dashboard#index"
  
  resource :dashboard
  resource :user_session
  
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  
  resources :projects do
    member do
      get :xml_export
      get :audits
      get :team
      get :add_users
      post :update_users
    end
    
    resource :dashboard, :controller => 'dashboard'
    
    resources :acceptance_tests do
      member do
        get :clone_acceptance
      end
      collection do
        get :export
        post :assign
      end
    end
    resources :releases do
      member do
        get :select_stories
        post :assign_stories
        post :remove_stories
      end
      
      resources :stories
    end
    
    resources :initiatives
    
    ## TODO => simiplify the stories routes, too many.
    
    resources :stories do
      member do
        get :audit
        get :take_ownership
        get :release_ownership
        get :assign_ownership
        post :assign
        # put :clone
        get :clone
        put :move_up # Get ready to remove this
        put :move_down # Get ready to remove this
        get :edit_numeric_priority
        put :set_numeric_priority
      end
      
      collection do
        get :search
        get :all
        get :cancelled
        get :export
        get :export_tasks
        get :bulk_create
        post :bulk_create
      end
      
      resources :tasks do
        member do
          get :take_ownership
          get :release_ownership
          get :assign_ownership
          post :assign
        end
      end
      resources :acceptance_tests
    end
    
    resources :milestones do
      collection do
        get :show_all
        get :show_recent
      end
    end
    
    resources :iterations do
      member do
        get :allocation
        get :select_stories
        post :assign_stories
        get :export
        get :export_tasks
      end
      collection do
        post :move_stories
      end
      
      resources :stories
    end
    
    resources :users do
      member do
        get :remove_from_project
      end
    end
  end
  resources :users do
    collection do
      get :forgot_password
      post :forgot_password
      get :reset_password
      put :reset_password
    end
  end
  
end

app/models/project.rb
require 'story_point_calc'

class Project < ActiveRecord::Base
  has_many :acceptance_tests, :dependent => :destroy
  has_many :initiatives, :dependent => :destroy
  has_many :iterations, :dependent => :destroy  
  has_many :milestones, :dependent => :destroy  
  has_many :project_memberships, :dependent => :destroy
  has_many :releases, :dependent => :destroy  
  has_many :stories, :extend => StoryPointCalc, :dependent => :destroy  
  has_many :tasks, :through => :stories
  has_many :users, :through => :project_memberships
  
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 100 }
  validates_numericality_of  :planned_iterations, :only_integer => true, :greater_than => 0, 
    :allow_nil => true, :message => "must be a positive number"
    
  def current_velocity
    return 0 if self.iterations.past.size == 0
    points_completed_for_velocity/self.iterations.past.size
  end

  def points_completed_for_velocity
    points_to_subtract = self.iterations.current.first ? self.iterations.current.first.stories.points_completed : 0
    self.stories.points_completed - points_to_subtract
  end

  def points_not_completed_for_velocity
    points_to_add = self.iterations.current.first ? self.iterations.current.first.stories.points_completed : 0
    self.stories.points_remaining + points_to_add
  end

  def users_available_for_addition
    User.order('last_name ASC, first_name ASC').all - self.users
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :require_user, :only => :audits

  def index
    respond_to do |format|
      format.html {
        @projects = current_user.admin? ? Project.all(:order => 'name ASC') : current_user.projects
      }
      format.xml {
        @projects = Project.find(:all)
        render :xml => @projects.to_xml(:include => :iterations)
      }
    end
  end

  def show
    respond_to do |format|
      format.html {
        redirect_to project_dashboard_path(current_project)
      }
      format.xml {
        render :xml => current_project.to_xml(:include => :iterations)
      }
    end
  end

  def team
    respond_to do |format|
      format.html {@users = current_project.users}
      format.js {
        render :update do |page|
          page.redirect_to team_project_path(current_project)
        end
      }
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new params[:project]
    
    if @project.save
      current_user.projects << @project if params[:add_me] == '1'
      render_success("New project \"#{@project.name}\" has been created.") { redirect_to projects_path }
    else
      render_errors(@project.errors.full_messages.to_sentence) { render :new }
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      render_success("Project \"#{current_project.name}\" has been updated.") { redirect_to projects_path }
    else
      render_errors(@project.errors.full_messages.to_sentence) { render :edit }
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:status] = "#{@project.name} has been deleted."
    redirect_to projects_path
  end

  def add_users
    @available_users = current_project.users_available_for_addition
    render :update do |page|
      page.call 'showPopup', render(:partial => 'add_users')
    end
  end

  def update_users
    users_added = []
    (params[:selected_users] || []).each do |uid|
      user = User.find_by_id(uid)
      if user
        current_project.users << user
        users_added << user.full_name
      end
    end
    flash[:status] = "The following users were added to the project: " + users_added.join(', ') unless users_added.empty?
    redirect_to team_project_path(current_project)
  end

  def audits
    @audits = Audit.find(:all, :conditions => ["project_id = #{params[:id]} AND object = 'Story'"], :order => "created_at DESC")
    render :layout => false
  end

  def xml_export
    respond_to do |format|
      format.js{
        render :update do |page|
         page.redirect_to formatted_xml_export_project_path(current_project, :xml)
        end
      }
      format.html{redirect_to formatted_xml_export_project_path(current_project, :xml)}
      format.xml{render :xml => current_project.to_xml(:include => { :iterations => { :include => { :stories => { :include => [:tasks, :acceptance_tests] } } } })  }
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def empty_projects_content(&block)
    yield if @projects.empty?
  end

  def project_audit_image(project)
    link_to image_tag("rss_small.png"), audits_project_path(project)
  end
  
  def project_export_image(project)
    link_to image_tag("xml.gif"), xml_export_project_path(project)
  end

  def project_dashboard_link(project)
    link_to project.name, project_path(project)
  end

  def link_to_view_team(project)
    link_to "View Team", team_project_path(project)
  end

  def link_to_edit_project(project)
    link_to "Edit", edit_project_path(project), :class => "form popup"
  end

  def link_to_delete_project(project)
    link_to "Delete", project_path(project), :class => "delete popup", "data-message" => 'Are you sure you want to delete?<br />All associated data will also be deleted. This action can not be undone.'
  end

  def link_to_export_project(project)
    link_to "Export", xml_export_project_path(project)
  end

  def link_to_remove_user(user)
    link_to "Remove From Project", remove_from_project_project_user_path(current_project, user), :method => :put
  end

  def link_to_add_users
    link_to "Add Users to Project", add_users_project_path(current_project)
  end
  
end

app/views/projects/_add_users.html.erb
<%= form_for :users, update_users_project_path(current_project), :method => :post do |f| %>
	<h1>Add users to <%= current_project.name %></h1>
	<table width="100%" cellspacing="0" cellpadding="3">
		<tr>
			<th>Available</th>
			<th> </th>
			<th>Selected</th>
		</tr>
		<tr>
			<td width="50%">
				<select multiple="multiple" size="10" id="Available" name="available" style="width: 100%;">
					<%= options_from_collection_for_select(@available_users, 'id', 'full_name') %>
				</select>
			</td>
			<td>
				<%#= button_to_function "&lt;&lt;", "move('Selected', 'Available');"%><br /><br />
				<%#= button_to_function "&gt;&gt;", "move('Available', 'Selected');"%>
			</td>
			<td width="50%">
				<select multiple="multiple" size="10" id="Selected" name="selected_users[]" style="width: 100%;"></select>
			</td>
		</tr>
	</table>
	<div class="submit">
		<%= submit_tag "Add Selected Users" %>
	</div>
<% end %>

app/views/projects/_form.html.erb
<h2>Project Details</h2>
<fieldset>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<%= form.label :planned_iterations, "Planned Iterations" %>
	<%= form.text_field :planned_iterations, :size => 3 %>
	<%= form.label :description %>
	<%= form.text_area :description %>
</fieldset>
<fieldset>
	<%= check_box_tag :add_me, '1', true %>
	<%= label :add_me, "Add my account to the project team" %>
</fieldset>

app/views/projects/_my_projects_list.html.erb
<div>
	<h3>My Projects:</h3>
	<ul id="project_list">
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project_dashboard_path(project) %></li>
	<% end %>
	</ul>
</div>

app/views/projects/edit.html.erb
<%= form_for current_project do |f| %>
	<%= render :partial => f %>
	<%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<p><strong><%= link_to 'Create New Project', new_project_path %></strong></p>

<% if @projects.present? %>
	<table class="sort-table" width="100%" id="projectsTable" cellspacing="0" cellpadding="3" border="0">
		<thead>
			<tr>
				<td>&nbsp;</td>
				<td>Projects</td>
				<td>Action</td>
			</tr>
		</thead>
		<tbody>
		<% @projects.each do |project| %>
			<tr class="<%= cycle("even_row", "odd_row") %>">
				<td width="4%"><%= project_audit_image(project) %></td>
				<td>
					<%= project_dashboard_link(project) %><br />
					<%= textilize(project.description) %>
				</td>
				<td class="actions">
					<%= link_to_view_team(project) %>
					<%= link_to_edit_project(project) %>
					<%= link_to_delete_project(project) %>
					<%= link_to_export_project(project) %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% else %>
	<p>You have no projects defined.</p>
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
	<%= render :partial => f %>
	<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<% if current_project.description? %>
	<div id="project_description">
		<strong>Description:</strong>
		<%= textilize(current_project.description) %>
	</div>
<% end %>

<%= milestones_calendar %>

<% if @stories.present? %>
<div>
	<h3>My Stories:</h3>
	<%= render :partial => 'stories/stories', :locals => {:hide_cols => [ :checkbox, :owner, :project ]} %>
</div>
<% end %>

<% if @tasks.present? %>
<div>
	<h3>My Tasks:</h3>
	<%= render :partial => 'tasks/tasks', :locals => {:hide_cols => [ :project, :owner ]} %>
</div>
<% end %>

app/views/projects/team.html.erb
<div>
	<h2>Project Team</h2>
	<p>The users shown here are part of the project team for <strong><%= current_project.name %></strong>.</p>
	<p>Admin accounts are marked with <%= image_tag('admin_dot.gif') %>.</p>
	<p><strong><%= link_to_add_users %></strong></p>
	<p><strong><%= link_to_new_project_user %></strong></p>
</div>
<div>
	<%= render :partial => 'users/user' %>
</div>