config/routes.rb
Explainpmt::Application.routes.draw do
  
  root :to => "dashboard#index"
  
  resource :dashboard
  resource :user_session
  
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  
  resources :projects do
    member do
      get :xml_export
      get :audits
      get :team
      get :add_users
      post :update_users
    end
    
    resource :dashboard, :controller => 'dashboard'
    
    resources :acceptance_tests do
      member do
        get :clone_acceptance
      end
      collection do
        get :export
        post :assign
      end
    end
    resources :releases do
      member do
        get :select_stories
        post :assign_stories
        post :remove_stories
      end
      
      resources :stories
    end
    
    resources :initiatives
    
    ## TODO => simiplify the stories routes, too many.
    
    resources :stories do
      member do
        get :audit
        get :take_ownership
        get :release_ownership
        get :assign_ownership
        post :assign
        # put :clone
        get :clone
        put :move_up # Get ready to remove this
        put :move_down # Get ready to remove this
        get :edit_numeric_priority
        put :set_numeric_priority
      end
      
      collection do
        get :search
        get :all
        get :cancelled
        get :export
        get :export_tasks
        get :bulk_create
        post :bulk_create
      end
      
      resources :tasks do
        member do
          get :take_ownership
          get :release_ownership
          get :assign_ownership
          post :assign
        end
      end
      resources :acceptance_tests
    end
    
    resources :milestones do
      collection do
        get :show_all
        get :show_recent
      end
    end
    
    resources :iterations do
      member do
        get :allocation
        get :select_stories
        post :assign_stories
        get :export
        get :export_tasks
      end
      collection do
        post :move_stories
      end
      
      resources :stories
    end
    
    resources :users do
      member do
        get :remove_from_project
      end
    end
  end
  resources :users do
    collection do
      get :forgot_password
      post :forgot_password
      get :reset_password
      put :reset_password
    end
  end
  
end

app/models/story.rb
require 'position'
class Story < ActiveRecord::Base
  include Position
  include AttributeMapper
  
  map_attribute :status, :to => {:new => 1, :defined => 2, :in_progress => 3, 
    :rejected => 4, :blocked => 5, :complete => 6, :accepted => 7, :cancelled => 8, :obstacle => 9}
    
  map_attribute :value, :to => {:high => 1, :med_high => 2, :medium => 3, :med_low => 4, :low => 5, :na => 6}
  map_attribute :risk, :to => {:high => 1, :normal => 2, :low => 3, :na => 4}
  
  belongs_to :project
  belongs_to :iteration
  belongs_to :initiative
  belongs_to :release
  belongs_to :creator, :class_name => 'User'
  belongs_to :updater, :class_name => 'User'
  belongs_to :owner, :class_name => 'User', :foreign_key => :user_id
  
  has_many :tasks, :dependent => :destroy
  has_many :acceptance_tests, :dependent => :destroy
  has_many  :audits,  :as => :auditable

  validates_presence_of :title, :project, :status
  validates_uniqueness_of :scid, :scope => :project_id
  validates_length_of :title, :maximum => 255
  validates_numericality_of :points, :only_integer => true, :greater_than_or_equal_to => 0, :message => "must be a positive integer", :if => proc{|x| x.iteration}
  
  scope :with_details, includes(:initiative, :project, :owner, :iteration, :release)
  scope :backlog, where(:iteration_id => nil)
  scope :cancelled, lambda{ backlog.where(:status => Story.statuses[:cancelled]) }
  scope :completed, lambda{ where(:status => [Story.statuses[:complete], Story.statuses[:accepted]]) }
  scope :incomplete, lambda{ where("stories.status not in (?)", [Story.statuses[:complete], Story.statuses[:accepted], Story.statuses[:cancelled]]) }
  scope :not_cancelled, lambda{ where("stories.status <> ?", Story.statuses[:cancelled]) }
  scope :not_estimated_and_not_cancelled, lambda{ not_cancelled.where(:points => nil) }
  scope :not_cancelled_and_not_assigned_to_an_iteration, lambda{ backlog.not_cancelled }
  scope :last_position, order("stories.position DESC").limit(1)
  scope :last_scid, order("stories.scid DESC").limit(1)  
  scope :for_user, lambda{|user| where(:user_id => user.id) }  
  
  before_validation :set_scid, :on => :create
  before_save   :before_save_reset_status
  
  def complete?
    [:accepted, :complete].include?(self.status)
  end
  
  def closed?
    [:accepted, :complete, :cancelled].include?(self.status)    
  end

  def assign_to!(new_owner)
    update_attribute(:user_id, new_owner.id)
  end

  def release_ownership!
    update_attribute(:user_id, nil)
  end

  def clone!
    self.clone.tap do |ac|
      ac.title = "Clone: #{title}"
      ac.save!
    end
  end

  def self.assign_many_to_iteration(iteration, stories)
    successes, failures = [], []
    stories.each do |s|
      s.iteration = iteration
      if s.save
        successes << "SC#{s.scid} has been moved."
      else
        failures << "SC#{s.scid} could not be moved. (make sure it is defined)"
      end
    end
    { :successes => successes, :failures => failures }
  end
  
  def self.assign_many_to_release(release, stories)
    successes, failures = [], []
    stories.each do |s|
      s.release = release
      if s.save
        successes << "SC#{s.scid} has been moved."
      else
        failures << "SC#{s.scid} could not be moved."
      end
    end
    { :successes => successes, :failures => failures }
  end
  
  protected

  def after_initialize
    self.status = :new unless self.status
    self.value = :na unless self.value
    self.risk = :normal unless self.risk
  end

  def set_scid
    self.scid = project.stories.last_scid.first.scid + 1 rescue 1
  end

  private

  def before_save_reset_status
    self.iteration = nil if status == :cancelled    
    self.owner = nil if self.iteration.nil?
    self.status = :in_progress if status == :defined and owner
    self.status = :defined if status == :new and self.points
  end
  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :find_story, :except => [:index, :new, :create, :audit, :export, :export_tasks, :bulk_create, :cancelled, :all, :search]

  def index
    @stories = current_project.stories.backlog.not_cancelled
    respond_to do |format|
      format.html
      format.xml { render :xml => @stories }
    end
  end
  
  ## TODO => make these specialized routes which pass a param or something to get into the real index method instead..
  def cancelled
    @stories = current_project.stories.cancelled
    render :index
  end

  def all
    @stories = current_project.stories
    render :index
  end

  def new
    @story = Story.new
  end

  def show
    @tasks = @story.tasks
    @acceptance_tests = @story.acceptance_tests
  end

  def create
    @story = Story.new params[:story]
    @story.project = current_project
    @story.iteration = Iteration.find params[:iteration_id] if params[:iteration_id]
    @story.creator_id = current_user.id
    
    if @story.save
      render_success('The new story card has been saved.') { redirect_to project_stories_path(current_project) }
    else
      render_errors(@story.errors.full_messages.to_sentence) { render :new }
    end
  end

  def update
    @story.attributes = params[:story]
    @story.updater_id = current_user.id
    
    if @story.save
      render_success('The changes to the story card have been saved.') { redirect_to project_stories_path(current_project) }
    else
      render_errors(@story.errors.full_messages.to_sentence) { render :edit }
    end
  end

  def take_ownership
    @story.assign_to!(current_user)
    redirect_to request.referer
  end

  def release_ownership
    @story.release_ownership!
    redirect_to request.referer
  end

  def assign_ownership
    @users = current_project.users
    render :partial => "assign_owner_form"
  end

  def assign
    @story.assign_to!(User.find params[:owner][:id])
    redirect_to project_story_path(current_project, @story)
  end

  def clone
    if story = @story.clone!
      render_success("New story \"#{story.title}\" has been created.") { redirect_to request.referer }
    else
      render_errors(@story.errors.full_messages.to_sentence) { redirect_to request.referer }
    end
  end

  def destroy
    if @story.destroy
      render_success("Story \"#{@story.title}\" has been deleted.") { redirect_to request.referer }
    else
      render_errors(@story.errors.full_messages.to_sentence) { redirect_to request.referer }
    end
  end

  def edit_numeric_priority
    respond_to do |format|
      format.js { render :partial => "stories/edit_numeric_priority_form" }
    end
  end

  def audit
    @changes = Story.find(params[:id]).audits.updates.includes(:user)
    respond_to do |format|
      format.js { render :partial => "stories/audit" }
    end
  end

  def export
    headers['Content-Type'] = "application/vnd.ms-excel"
    @stories = current_project.stories
    render :layout => false
  end
  alias :export_tasks :export

  def bulk_create
    if request.get?
      render :partial => 'bulk_create_form'
    else
      st = params[:story][:titles]
      if st.present?
        params[:story][:titles].each_line do |title|
          current_project.stories.create(:title => title, :creator_id => current_user.id)
        end
        render_success("New story cards created.") do
          redirect_to project_stories_path(current_project)
        end
      else
        render_errors("Please enter at least one story card title.") do
          redirect_to project_stories_path(current_project)
        end
      end
    end
  end

  def search
    query = params[:query_stories]
    unless query.blank?
      @stories = current_project.stories.find(:all, :conditions => "stories.scid = '#{query[2..-1]}' or stories.title like '%#{query}%' or stories.description like '%#{query}%'")
    else
      @stories = current_project.stories.backlog.not_cancelled
    end
    render :partial => 'backlog'
  end

  protected

  def find_story
    @story = Story.find params[:id]
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
  
  def link_to_new_story
    link_to 'Create Story Card', new_project_story_path(current_project), :class => "form popup"
  end

  def link_to_show_cancelled
    nav_item 'Show Cancelled', cancelled_project_stories_path(current_project)
  end
  
  def link_to_show_all
    nav_item 'Show All', all_project_stories_path(current_project)
  end

  def link_to_new_iteration_story(iteration)
    link_to 'Create Story Card', new_project_iteration_story_path(current_project, iteration), :class => "form popup"
  end

  def link_to_new_stories
    link_to 'Bulk Create', bulk_create_project_stories_path(current_project)
  end

  def link_to_story_with_sc(story)
    link_to("SC#{story.scid}", project_story_path(current_project, story)) + '(' + truncate(story.title, :length => 30) + ')'
  end

  def link_to_story(story, options={})
    link_to(options[:text] || story.title, project_story_path(story.project, story))
  end

  def link_to_assign_story_ownership(story)
    link_to 'assign', assign_ownership_project_story_path(current_project, story)
  end

  def link_to_take_story_ownership(story)
    link_to('take', take_ownership_project_story_path(current_project, story), :method => :put)
  end

  def link_to_release_story_ownership(story)
    link_to('release', release_ownership_project_story_path(current_project, story), :method => :put)
  end

  def link_to_new_acceptance_for(story)
    link_to 'Add Acceptance', new_project_story_acceptance_test_path(current_project, story), :class => "form popup"
  end

  def link_to_export_stories
    link_to 'Export All Stories', export_project_stories_path(current_project)
  end

  def link_to_export_tasks
    link_to 'Export All Tasks', export_tasks_project_stories_path(current_project)
  end

  def story_select_list_for(stories)
    stories.inject(""){|options, story| options << "<option value='#{story.id}'>SC#{story.scid}  (#{truncate(story.title, :length => 30)})</option>"}
  end

  def link_to_audit_story(story)
    link_to "View History", audit_project_story_path(current_project, story)
  end

  def link_to_edit_story(story)
    link_to "Edit", edit_project_story_path(current_project, story), :class => "form popup edit tip", :title => "edit"
  end

  def link_to_clone_story(story)
    link_to "Clone", clone_project_story_path(current_project, story)
  end

  def link_to_move_story_up(story)
    link_to "Move Up", move_up_project_story_path(current_project, story)
  end

  def link_to_move_story_down(story)
    link_to "Move Down", move_down_project_story_path(current_project, story)
  end

  def link_to_edit_story_position(story)
    link_to "Insert At", edit_numeric_priority_project_story_path(current_project, story), :class => "form popup"
  end

  def link_to_delete_story(story)
    link_to "Delete", project_story_path(current_project, story), :class => "delete popup tip", "data-message" => 'Are you sure you want to delete?<br />All associated data will also be deleted. This action can not be undone.', :title => "delete"
  end

  def link_to_audit_story(story)
    link_to "View History", audit_project_story_path(current_project, story), :class => "view popup tip", :title => "view"
  end
  
end

app/views/stories/_assign_owner_form.html.erb
<%= form_for :owner, assign_project_story_path(current_project, @story) do |f| %>
	<% @users.each do |m| %>
		<%= f.radio_button :id, m.id %>
		<%= f.label :id, m.full_name, :value => m.id, :class => "inline" %>
		<br />
	<% end %>
	<div class="submit">
		<%= f.submit "Assign" %>
	</div>
<% end %>

app/views/stories/_audit.html.erb
<% if @changes.present? %>
	<table class="sort-table" width="100%" id="story_audit" cellspacing="0" cellpadding="0" border="0">
		<thead>
			<tr>
				<td>Time</td>
				<td>Before</td>
				<td>After</td>
				<td>User</td>
			</tr>
		</thead>
		<tbody>
		<% @changes.each do |change| %>
			<tr class="<%= cycle("even_row", "odd_row") %>">
				<td><%= change.created_at %></td>
				<% logger.debug '*'*90 %>
				<% logger.debug change.auditable_changes.inspect %>
				<td><%#= text_area_tag "body", change.before, :size => "30x3", :readonly => "true", :style => "background:#E6E6E6" %></td>
				<td><%#= text_area_tag "body", change.after, :size => "30x3", :readonly => "true", :style => "background:#E6E6E6" %></td>
				<td><%= change.user.full_name %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% else %>
	<p>No Changes have been recorded for this story</p>
<% end %>

app/views/stories/_backlog.html.erb
<% if @stories.present? %>
	<%= form_tag move_stories_project_iterations_path(current_project) %>
		<%#= render :partial => 'stories/move_stories_form', :locals => { :default => "Not Assigned", :selected_id => 'select1' } %>
		<%= render :partial => 'stories/stories' , :locals => { :hide_cols => [:project] } %>
		<% if @stories.size > 10 %>
			<br />
			<%= render :partial => 'stories/story_links' %>
			<%= render :partial => 'stories/move_stories_form', :locals => { :default => "Not Assigned", :selected_id => 'select2' } %>
		<% end %>
	</form>
<% end %>

app/views/stories/_bulk_create_form.html.erb
<%= form_for :story, :url => bulk_create_project_stories_path(current_project) do |f| %>
	<h2>Bulk Story Card Creation</h2>
	<fieldset>
		<%= label_tag :titles, "Enter titles of new storycards, one per line:" %>
		<%= f.text_area :titles, :cols => 71, :rows => 16, :class => 'large' %>
	</fieldset>
	<div class="submit">
		<%= f.submit "Create Story Cards" %>
	</div>
<% end %>

app/views/stories/_form.html.erb
<h2>Story Card Details</h2>
<fieldset>
	<%= form.label :title %>
	<%= form.text_area :title %>
	<%= form.label :initiative_id %>
	<%= form.select :initiative_id, current_project.initiatives.map{|x|[x.name, x.id]}, :include_blank => true %>
	<%= form.label :release_id %>
	<%= form.select :release_id, current_project.releases.map{|x|[x.name, x.id]}, :include_blank => true %>
	<%= form.label :customer %>
	<%= form.text_field :customer %>
</fieldset>
<fieldset>
	<%= form.label :status %>
	<%= form.select :status, Story.statuses.collect{|k,v|[k.to_s.titleize, k] }%>
	<%= form.label :value %>
	<%= form.select :value, Story.values.collect{|k,v|[k.to_s.titleize, k] }%>
	<%= form.label :risk %>
	<%= form.select :risk, Story.risks.collect{|k,v|[k.to_s.titleize, k] }%>
</fieldset>
<fieldset>
	<%= form.label :points %>
	<%= form.text_field :points, :size => 2 %>
	<%= form.label :description %>
	<%= form.text_area :description %>
</fieldset>

app/views/stories/_move_stories_form.html.erb
<% iterations = current_project.iterations%>
<div class="move_to">
	<% if iterations.present? %>
	<%= hidden_field_tag :move_to %>
    Move Selected Story Cards to:
    <%= select_tag selected_id, iteration_select_list_for(iterations, default) %>
    <%= submit_tag "Go" %>
	<% else %>
	<span style="color: #FF0000;">No iterations to move story cards to.</span>
	<% end %>
</div>

app/views/stories/_stories.html.erb
<% hide_cols ||= [] %>
<table class="sorting" id="backlog_stories">
	<thead>
		<tr>
			<th class="checkers"><input type="checkbox" class="checkall" /></th>
			<th class="align_left">SCID</th>
			<%= column_content_for(hide_cols, :project) do %><th class="align_left center">Project</th><% end %>
			<th class="align_left center">Title</th>
			<th class="align_left center">Initiative</th>
			<%= column_content_for(hide_cols, :release) do %><th class="align_left center">Release</th><% end %>
			<th class="align_left center">Points</th>
			<th class="align_left center">Value</th>
			<th class="align_left center">Risk</th>
			<th class="align_left center">Status</th>
			<%= column_content_for(hide_cols, :owner) do %><th class="align_left center">Owner</th><% end %>
			<%= column_content_for(hide_cols, :iteration) do %><th class="align_left center">Iteration</th><% end %>
			<th class="align_left center">Customer</th>
			<th class="align_left center">#</th>
			<%= column_content_for(hide_cols, :action) do %><th class="align_left center tools">Action</th><% end %>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => @stories, :locals => { :hide_cols => hide_cols } %>
	</tbody>
</table>
<div class="table_actions">
	<input type="checkbox" class="checkall" />
	
	<select>
		<option>Choose action</option>
		<option>Delete</option>
	</select>
	
	<button class="left">Apply to Selected</button>
</div>

app/views/stories/_story.html.erb
<tr class="<%= cycle("even_row", "odd_row") %>">
	<%= column_content_for(hide_cols, :checkbox) do %>
		<td class="checkers"><%= check_box_tag 'selected_stories[]', story.id, false, :id => "sc_check_#{story.id}" %></td>
	<% end %>
	<td class="align_left center">
		<label class="inline" for="sc_check_<%= story.id %>"><%= "SC#{story.scid}" %></label>
	</td>

	<%= column_content_for(hide_cols, :project ) do %>
	<td class="align_left center"><%= link_to(story.project.name, project_dashboard_path(story.project)) %></td>
	<% end %>

	<td class="align_left center"><%= link_to_story(story) %></td>
	<td class="align_left center"><%= story.initiative_id? ? link_to_edit_initiative(story.initiative, :class => "popup") : "Not Assigned" %></td>
	
	<%= column_content_for(hide_cols, :release ) do %>
	<td class="align_left center"><%= story.release_id? ? link_to_release(story.release) : "Not Assigned" %></td>
	<% end %>
	
	<td class="align_left center"><%= story.points %></td>
	
	<%= column_content_for(hide_cols, :value_risk) do %>
	<td class="align_left center"><%= story.value %></td>
	<td class="align_left center"><%= story.risk %></td>
	<% end %>
	
	<td class="align_left center"><%= story.status %></td>
	
	<% unless hide_cols.include?( :owner ) %>
	<td class="align_left center">
	<% if story.owner%>
		<%= story.owner.full_name %><%= '- ' + story.owner.team if story.owner.team? %>
		<%= '(' + link_to_release_story_ownership(story) + ')' %>
	<% elsif story.iteration  %>
		<%='None (' + link_to_take_story_ownership(story) + '/' + link_to_assign_story_ownership(story) + ')'%>
	<% end %>
	</td>
	<% end %>
	<%= column_content_for(hide_cols, :iteration ) do %>
	<td class="align_left center"><%= story.iteration_id? ? link_to_iteration(story.iteration) : "Not Assigned" %></td>
	<% end %>
	<td class="align_left center"><%= story.customer %></td>
	
	<%= column_content_for(hide_cols, :position) do %>
	<td class="align_left center"><%= story.position %></td>
	<% end %>
	
	<%= column_content_for(hide_cols, :action) do %>
	<td class="align_left center tools">
		<%= link_to_edit_story(story) %>
		<%= link_to_delete_story(story) %>
		<%= link_to_audit_story(story) %>
	</td>
	<% end %>
</tr>

app/views/stories/_story_links.html.erb
<li><%= link_to_new_story %></li>
<li><%= link_to_new_stories %></li>
<li><%= link_to_export_stories %></li>
<li><%= link_to_export_tasks %></li>

app/views/stories/edit.html.erb
<%= form_for [current_project, @story] do |f| %>
	<%= render :partial => f %>
	<%= f.submit %>
<% end %>

app/views/stories/export.html.erb
<table cellspacing="0" cellpadding="0" border="0" width="100%">
	<thead>
		<tr>
			<th><big>Project: <%= current_project.name %></big></th>
		</tr>
		<tr>
			<th>SCID</th>
			<th>Title</th>
			<th>Description</th>
			<th>Initiative</th>
			<th>Release</th>
			<th>Points</th>
			<th>Value</th>
			<th>Risk</th>
			<th>Status</th>
			<th>Iteration</th>
			<th>Customer</th>
			<th>Owner</th>
		</tr>
	</thead>
	<tbody>
	<% @stories.each do |story| %>
		<tr>
			<td><%= story.scid %></td>
			<td><%= story.title %></td>
			<td><%= story.description %></td>
			<td><%= story.initiative_id? ? story.initiative.name : "Not Assigned" %></td>
			<td><%= story.release_id? ? story.release.name : "Not Assigned" %></td>
			<td><%= story.points %></td>
			<td><%= story.value.name %></td>
			<td><%= story.risk.name %></td>
			<td><%= story.status.name %></td>
			<td><%= story.iteration_id? ? story.iteration.name : "Not Assigned" %></td>
			<td><%= story.customer %></td>
			<td><%= story.owner ?  story.owner.full_name : "Not Assigned" %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/stories/export_tasks.html.erb
<table cellspacing="0" cellpadding="0" border="0" width="100%">
	<thead>
		<th>SCID</th>
		<th>Story Title</th>
		<th>Task Name</th>
		<th>Description</th>
		<th>Owner</th>
		<th>Complete</th>
	</thead>
	<tbody>
	<% @stories.each do |story| %>
		<% story.tasks.each do |task| %>
		<tr>
			<td>SC<%= story.scid %></td>
			<td><%= story.title %></td>
			<td><%= task.name %></td>
			<td><%= task.description%></td>
			<td><%= task.owner ? task.owner.full_name : "Not Assigned"%></td>
			<td><%= task.complete ? "Yes" : "No" %></td>
		</tr>
		<% end %>
	<% end %>
  	</tbody>
</table>

app/views/stories/index.html.erb
<div class="box_top">
	<h2>Backlog</h2>
	
	<ul class="sorting">
		<%= render :partial => "story_links" %>
		<%= link_to_show_cancelled %>
		<%= link_to_show_all %>
	</ul>
</div>

<%= content_for(:story_search_form, '') %>

<% if @stories.blank? %>
	<div class="box_content padding">
		<p>No active stories are in the project backlog.</p>
	</div>
<% else %>
	<div class="box_content" id="story_backlog">
		<%= render :partial => 'backlog' %>
	</div>
<% end %>

app/views/stories/show.html.erb
<br />
(<%= link_to_edit_story(@story) %>)
(<%= link_to_new_task(@story) %>)
(<%= link_to_new_acceptance_for(@story) %>)
(<%= link_to_audit_story(@story) %>)<br /><br />
<h3><%= "SC#{@story.scid} #{@story.title}" %></h3>
<table cellspacing="0" cellpadding="3" border="0" style="float: left; margin-right: 20px;">
	<tr class="even_row">
		<td><strong>Created</strong></td>
		<td class="align_right"><%= short_date(@story.created_at) if @story.created_at%> <%= "(#{@story.creator.full_name})" if @story.creator %></td>
	</tr>
	<tr class="odd_row">
		<td><strong>Updated</strong></td>
		<td class="align_right"><%= short_date(@story.updated_at) if @story.updated_at%> <%= "(#{@story.updater.full_name})" if @story.updater %></td>
	</tr>
	<tr class="even_row">
		<td><strong>Initiative</strong></td>
		<td class="align_right"><%= @story.initiative.name  if @story.initiative %></td>
	</tr>
</table>

<table cellspacing="0" cellpadding="3" border="0" style="float: left; margin-right: 20px;">
	<tr class="even_row">
		<td><strong>Value</strong></td>
		<td class="align_right"><%= @story.value %></td>
	</tr>
	<tr class="odd_row">
		<td><strong>Risk</strong></td>
		<td class="align_right"><%= @story.risk %></td>
	</tr>
	<tr class="even_row">
		<td><strong>Status</strong></td>
		<td class="align_right"><%= @story.status %></td>
	</tr>
</table>

<table cellspacing="0" cellpadding="3" border="0" style="float: left; margin-right: 20px;">
	<tr class="even_row">
		<td><strong>Owner</strong></td>
		<td class="align_right">
		<% if @story.owner %>
			<%= @story.owner.full_name %><%= '- ' + @story.owner.team if @story.owner.team? %>
			<%= '(' + link_to_release_story_ownership(@story) + ')' %>
		<% elsif @story.iteration %>
			<%='None (' + link_to_take_story_ownership(@story) + '/' + link_to_assign_story_ownership(@story) + ')'%>
		<% end %>
		</td>
	</tr>
	<tr class="odd_row">
		<td><strong>Estimate</strong></td>
		<td class="align_right"><%= @story.points if @story.points %></td>
	</tr>
	<tr class="even_row">
		<td><strong>Release</strong></td>
		<td class="align_right"><%= @story.release.name  if @story.release %></td>
	</tr>
</table>
<div style="clear:both;"></div>
<% unless @story.description.blank? %>
	<label><strong>Description</label></strong>
	<%= textilize(@story.description) %>
<% end %><br />
<h3>Tasks</h3>
<% if @tasks.present? %>
	<%= render :partial => 'tasks/tasks', :locals => {:hide_cols => [ :project, :story, :iteration ]} %>
<% else %>
	<p>No tasks have been defined for this story.</p>
<% end %>

<br /><br />

<h3>Acceptance Tests</h3>
<% if @acceptance_tests.present? %>
	<%= render( :partial => 'acceptance_tests/acceptance_tests', :locals => {:hide_cols => [ :checkbox, :story, :iteration ]}) %>
<% else %>
	<p>No acceptance tests have been defined for this story.</p>
<% end %>